[package]
name = "text-rts"
version = "0.1.0"
authors = ["Maxwell Anderson <maxwell.brayden.anderson@gmail.com>"]
edition = "2018"

[dependencies]
bracket-lib = { git = "https://github.com/thebracket/bracket-lib", features = ["threaded"]}
legion = "0.2"